version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: db_colegio
      MYSQL_ROOT_PASSWORD: alumno123
    ports:
      - "3306:3306"
    networks:
      - colegio-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  ms-academico:
    build: ./backend/ms-academico
    ports:
      - "8080:8080"
    networks:
      - colegio-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: alumno123

  ms-asistencia:
    build: ./backend/ms-asistencia
    ports:
      - "8081:8080"
    networks:
      - colegio-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: alumno123

  ms-comunicaciones:
    build: ./backend/ms-comunicaciones
    ports:
      - "8083:8080"
    networks:
      - colegio-net
    depends_on:
      db:
        condition: service_healthy

  bff-service:
    build: ./backend/bff-service
    ports:
      - "8082:8080"
    networks:
      - colegio-net
    depends_on:
      ms-academico:
        condition: service_started
      ms-asistencia:
        condition: service_started
      ms-comunicaciones:
        condition: service_started
    environment:
      URL_ACADEMICO: "http://ms-academico:8080/api/estudiantes"
      URL_ASISTENCIA: "http://ms-asistencia:8080/api/asistencia"
      URL_COMUNICACIONES: "http://ms-comunicaciones:8080/api/comunicaciones/resumen"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - colegio-net
    depends_on:
      bff-service:
        condition: service_started

networks:
  colegio-net:
    driver: bridge